SELECT RTRIM(I.IXOWNER),
       RTRIM(I.IXNAME),
       RTRIM(T.TBLOWNER),
       RTRIM(T.TBLNAME),
       I.IXTYPE,
       I.ISUNIQUE,
       I.ISPRIMARY,
       I.KEYCNT,
       I.PAGESPARAM
FROM SYS.INDEXES I
JOIN SYS.TABLES T ON T.TBLID = I.TBLID
WHERE T.TBLOWNER NOT IN ('SYS', 'TTREP', 'TIMESTEN')
  AND ROWNUM <= 501
ORDER BY T.TBLOWNER, T.TBLNAME, I.IXNAME

