SELECT RTRIM(REPLICATION_OWNER),
       RTRIM(REPLICATION_NAME),
       SUBSCRIBER_ID,
       TRACK_ID,
       STATE,
       LATENCY,
       TIMESEND,
       TIMERECV
FROM TTREP.REPPEERS
ORDER BY REPLICATION_OWNER, REPLICATION_NAME, SUBSCRIBER_ID, TRACK_ID

