SELECT PERM_ALLOCATED_SIZE,
       PERM_IN_USE_SIZE,
       PERM_IN_USE_HIGH_WATER,
       TEMP_ALLOCATED_SIZE,
       TEMP_IN_USE_SIZE,
       TEMP_IN_USE_HIGH_WATER,
       REQUIRED_RECOVERY,
       FIRST_LOG_FILE,
       LAST_LOG_FILE,
       REPHOLD_LOG_FILE
FROM SYS.MONITOR

