SELECT RTRIM(T.TBLOWNER),
       RTRIM(T.TBLNAME),
       T.NUMTUPS,
       T.NUMCOLS,
       T.LENGTH,
       S.LASTSTATSUPDATE
FROM SYS.TABLES T
LEFT OUTER JOIN SYS.TBL_STATS S ON S.TBLID = T.TBLID
WHERE T.TBLOWNER NOT IN ('SYS', 'TTREP', 'TIMESTEN')
  AND ROWNUM <= 501
ORDER BY T.TBLOWNER, T.TBLNAME

