SELECT H.SQLCMDID,
       C.SQL_HASH,
       RTRIM(C.OWNER),
       H.EXECUTIONS,
       H.MINEXECUTETIME,
       H.MAXEXECUTETIME,
       H.LASTEXECUTETIME,
       C.QUERYTEXT,
       H.COLLECTED_AT
FROM SYS.TTSTATS_SQL_COMMAND_HIST H
JOIN SYS.TTSTATS_TOP_SQL_CMD_TEXT C ON C.SQLCMDID = H.SQLCMDID
WHERE ROWNUM <= 20
ORDER BY H.MAXEXECUTETIME DESC

